exports.teams = [
  {
    team: "BASELINE",
    affiliation: "",
    country: "",
    registrationDate: "",
    contact: "",
    email: "",
    repo:
      "https://bitbucket.org/covid19-mlia/sample-participant-repository.git",
  },
  {
    team: "ETRANSLATION",
    affiliation: "European Commission, DGT and CNECT",
    country: "Luxembourg",
    registrationDate: "2020-10-21T18:30:26+0200",
    contact: "Andreas Eisele",
    email: "andreas.eisele@ec.europa.eu",
    repo: "https://bitbucket.org/covid19-mlia/etranslation.git",
  },
  {
    team: "PROMT",
    affiliation: "PROMT LLC",
    country: "Russian Federation",
    registrationDate: "2020-11-27T11:18:54+0100",
    contact: "Alexander Molchanov",
    email: "alexander.molchanov@promt.ru",
    repo: "https://bitbucket.org/covid19-mlia/promt.git",
  },
  {
    team: "NUIG-ULD",
    affiliation:
      "Data Science Institute (DSI), National University of Ireland, Galway",
    country: "Ireland",
    registrationDate: "2020-10-21T00:50:00+0200",
    contact: "Atul Kr. Ojha",
    email: "atul.kumar@insight-centre.org",
    repo: "https://bitbucket.org/covid19-mlia/nuig-uld.git",
  },
  {
    team: "BY",
    affiliation: "Yunnan University",
    country: "China",
    registrationDate: "2020-10-30T09:09:02+0100",
    contact: "Yang Bai",
    email: "baiyang.top@gmail.com",
    repo: "https://bitbucket.org/covid19-mlia/by.git",
  },
  {
    team: "IRSI",
    affiliation: "IRSI",
    country: "India",
    registrationDate: "2020-10-21T14:47:25+0200",
    contact: "Ayan Bandyopadhyay",
    email: "bandyopadhyay.ayan@gmail.com",
    repo: "https://bitbucket.org/covid19-mlia/irsi.git",
  },
  {
    team: "SSN_JB_TTM",
    affiliation: "Sri Sivasubramaniya Nadar College of Engineering",
    country: "India",
    registrationDate: "2020-11-05T05:12:39+0100",
    contact: "Bhuvana J",
    email: "bhuvanaj@ssn.edu.in",
    repo: "https://bitbucket.org/covid19-mlia/ssnjbttm.git",
  },
  {
    team: "IR_BITS",
    affiliation: "BIT Sindri",
    country: "India",
    registrationDate: "2020-11-05T08:37:25+0100",
    contact: "Dinesh Kumar Prabhakar",
    email: "dinesh.nitr@gmail.com",
    repo: "https://bitbucket.org/covid19-mlia/irbits.git",
  },
  {
    team: "GATENLP",
    affiliation: "University of Sheffield",
    country: "United Kingdom",
    registrationDate: "2020-10-22T13:16:57+0200",
    contact: "Carolina Scarton",
    email: "gatenlp.team@gmail.com",
    repo: "https://bitbucket.org/covid19-mlia/gatenlp.git",
  },
  {
    team: "HULAT-ISB",
    affiliation:
      "COMPUTER SCIENCE DEPARTMENT, UNIVERSIDAD CARLOS III DE MADRID",
    country: "Spain",
    registrationDate: "2020-10-20T10:08:24+0200",
    contact: "ISABEL SEGURA BEDMAR",
    email: "ISEGURA@INF.UC3M.ES",
    repo: "https://bitbucket.org/covid19-mlia/hulat-isb.git",
  },
  {
    team: "CUNI-MT",
    affiliation: "Charles University",
    country: "Czech Republic",
    registrationDate: "2020-11-11T10:29:35+0100",
    contact: "Ivana Kvapilikova",
    email: "kvapilikova@ufal.mff.cuni.cz",
    repo: "https://bitbucket.org/covid19-mlia/cunimt.git",
  },
  {
    team: "CUNI-MTIR",
    affiliation: "Charles University",
    country: "Czech Republic",
    registrationDate: "2020-11-11T11:31:28+0100",
    contact: "Shadi Saleh",
    email: "saleh@ufal.mff.cuni.cz",
    repo: "https://bitbucket.org/covid19-mlia/cunimtir.git",
  },
  {
    team: "NLP_TALENT",
    affiliation: "Universite du Quebec a Montreal",
    country: "Canada",
    registrationDate: "2020-10-22T21:47:20+0200",
    contact: "Tan Le",
    email: "letan.dhcn@gmail.com",
    repo: "https://bitbucket.org/covid19-mlia/nlptalent.git",
  },
  {
    team: "JUSTMT",
    affiliation: "Jordan University of Science and Technology",
    country: "Jordan",
    registrationDate: "2020-10-24T11:02:14+0200",
    contact: "Nabeel Ayyad",
    email: "nabeelbassam98@gmail.com",
    repo: "https://bitbucket.org/covid19-mlia/justmt.git",
  },
  {
    team: "CNLP-NITS-PP",
    affiliation: "National Institute of Technology Silchar",
    country: "India",
    registrationDate: "2020-10-20T09:49:41+0200",
    contact: "Dr. Partha Pakray",
    email: "partha@cse.nits.ac.in",
    repo: "https://bitbucket.org/covid19-mlia/cnlp-nits-pp.git",
  },
  {
    team: "LC",
    affiliation: "",
    country: "France",
    registrationDate: "2020-11-02T13:32:07+0100",
    contact: "Raheel Qader",
    email: "raheel.qader@linguacustodia.com",
    repo: "https://bitbucket.org/covid19-mlia/lc.git",
  },
  {
    team: "SU-NLP",
    affiliation: "Sabanc? University",
    country: "Turkey",
    registrationDate: "2020-10-28T22:23:43+0100",
    contact: "Reyyan Yeniterzi",
    email: "reyyan.yeniterzi@sabanciuniv.edu",
    repo: "https://bitbucket.org/covid19-mlia/sunlp.git",
  },
  {
    team: "TARJAMA-AI",
    affiliation: "Tarjama FZ LLC",
    country: "Jordan",
    registrationDate: "2020-10-21T16:47:41+0200",
    contact: "Ruba Jaikat",
    email: "ruba.jaikat@tarjama.com",
    repo: "https://bitbucket.org/covid19-mlia/tarjama-ai.git",
  },
  {
    team: "LIMSI",
    affiliation: "TLP, CNRS-LIMSI",
    country: "France",
    registrationDate: "2020-11-02T20:06:19+0100",
    contact: "Sadaf Abdul Rauf",
    email: "sadaf.abdulrauf@gmail.com",
    repo: "https://bitbucket.org/covid19-mlia/limsi.git",
  },
  {
    team: "NLP-UQAM",
    affiliation: "UQAM",
    country: "Canada",
    registrationDate: "2020-11-05T16:54:17+0100",
    contact: "Fatiha SAdat",
    email: "sadat.fatiha@uqam.ca",
    repo: "https://bitbucket.org/covid19-mlia/nlpuqam.git",
  },
  {
    team: "UB_BW",
    affiliation: "University of Botswana",
    country: "Botswana",
    registrationDate: "2020-10-21T20:55:02+0200",
    contact: "Edwin Thuma",
    email: "thumae@ub.ac.bw",
    repo: "https://bitbucket.org/covid19-mlia/ubbw.git",
  },
  {
    team: "DUT_NLP",
    affiliation: "Dalian University of Technology",
    country: "China",
    registrationDate: "2020-11-05T07:02:05+0100",
    contact: "Huiwei Zhou",
    email: "zhouhuiwei@dlut.edu.cn",
    repo: "https://bitbucket.org/covid19-mlia/dutnlp.git",
  },
  {
    team: "AMINE_TEAM",
    affiliation: "CERIST",
    country: "Algeria",
    registrationDate: "2020-11-25T13:25:53+0100",
    contact: "Amine Aliane",
    email: "aliane781@gmail.com",
    repo: "https://bitbucket.org/covid19-mlia/cerist.git",
  },
  {
    team: "ACCENTURE",
    affiliation: "",
    country: "",
    registrationDate: "",
    contact: "",
    email: "",
    repo: "https://bitbucket.org/covid19-mlia/accenture.git",
  },
];
